owner: "53354553"
team: "14417725"
lastUpdatedBy: "53354553"
lastRevision: 1773982118000
name: Uncle Robert Site
color: null
values:
  - key: bearerToken
    value: ""
    enabled: true
  - key: baseUrl
    value: https://api.unclerobertconsulting.com
    enabled: true
createdAt: 2026-03-20T04:28:40.000Z
updatedAt: 2026-03-20T04:48:38.000Z
