patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch
overrides:
  tailwindcss>nanoid: 3.3.8
  nanoid: ^3.3.8
  esbuild: 0.25.10
  lodash-es: 4.18.0
  mdast-util-to-hast: 13.2.1
  path-to-regexp: 0.1.13
  picomatch: 4.0.4
  qs: 6.15.2
  rollup: 4.59.0
  uuid: 11.1.1
  undici: ^6.19.0
  js-yaml: ^4.1.0
  react-router: ^6.28.1
  react-router-dom: ^6.28.1
  ip-address: ^9.0.5
  socket.io: ^4.7.5
  postcss: ^8.4.31
  brace-expansion: ^2.0.1
  tar: ^6.2.1
  decompress: ^4.2.1
