import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

/**
 * Public, read-only client view of real run state (Tier 1 item 3).
 *
 * Access is purely via the share token in the URL. There is no auth here and
 * no mutation surface: every fetch is a GET with the token attached, and the
 * server resolves the workspace from the token hash. All figures rendered are
 * the database values — no fallbacks, no defaults, no demo data.
 */

type SharedRun = {
  id: string;
  workflowId: string;
  workflowName?: string;
  status: string;
  triggerSource: string;
  startedAt: string | null;
  completedAt: string | null;
  errorMessage: string | null;
  createdAt: string;
};

type SharedRunDetail = {
  run: Omit<SharedRun, "workflowId" | "createdAt">;
  workflow: { id: string; name: string; description: string | null } | null;
  steps: Array<{
    id: string;
    status: string;
    startedAt: string | null;
    completedAt: string | null;
    latencyMs: number | null;
    cost: string | null;
    errorMessage: string | null;
  }>;
  artifacts: Array<{
    id: string;
    title: string;
    artifactType: string;
    status: string;
    summary: string | null;
    content: string;
    qualityScore: number | null;
    qualityGrade: string | null;
    verificationNotes: unknown;
    createdAt: string;
  }>;
  totalCost: string;
  totalLatencyMs: number;
};

const STATUS_STYLES: Record<string, string> = {
  completed: "bg-emerald-100 text-emerald-800",
  running: "bg-blue-100 text-blue-800",
  pending: "bg-slate-100 text-slate-700",
  paused_for_approval: "bg-amber-100 text-amber-800",
  failed: "bg-red-100 text-red-800",
  cancelled: "bg-zinc-200 text-zinc-700",
  draft: "bg-slate-100 text-slate-700",
  scheduled: "bg-blue-50 text-blue-700",
  published: "bg-emerald-50 text-emerald-700",
  archived: "bg-zinc-100 text-zinc-600",
};

function StatusBadge({ status }: { status: string }) {
  return (
    <Badge className={(STATUS_STYLES[status] || "bg-slate-100 text-slate-700") + " border-0"}>
      {status.replaceAll("_", " ")}
    </Badge>
  );
}

async function sharedFetch<T>(path: string, token: string): Promise<T> {
  const sep = path.includes("?") ? "&" : "?";
  const res = await fetch(`${path}${sep}token=${encodeURIComponent(token)}`);
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error((body as any).error || `Request failed (${res.status})`);
  }
  return res.json();
}

export default function SharedRuns() {
  const token = new URLSearchParams(window.location.search).get("token") || "";

  const runs = useQuery<{ runs: SharedRun[]; label: string | null }>({
    queryKey: ["shared-runs", token],
    queryFn: () => sharedFetch("/api/share/runs", token),
    enabled: !!token,
    refetchInterval: 15000,
  });

  const [selectedId, setSelectedId] = useState<string | null>(null);

  const detail = useQuery<SharedRunDetail>({
    queryKey: ["shared-run-detail", token, selectedId],
    queryFn: () => sharedFetch(`/api/share/runs/${selectedId}`, token),
    enabled: !!token && !!selectedId,
  });

  if (!token) {
    return (
      <HonestEmpty
        title="Share link required"
        body="Open the exact link your account manager sent you. It should look like /shared/runs?token=…"
      />
    );
  }

  if (runs.isError) {
    return (
      <HonestEmpty
        title="This share link is invalid or has been revoked"
        body={(runs.error as Error).message}
      />
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 p-6">
      <div className="mx-auto max-w-5xl space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">
            Run Report{runs.data?.label ? ` — ${runs.data.label}` : ""}
          </h1>
          <p className="text-sm text-slate-500">
            Read-only view generated by AgentLab OS. Every status, cost, and artifact below is
            the live database value for your workflows — nothing is simulated or cached.
          </p>
        </div>

        {runs.isLoading && <p className="text-sm text-slate-500">Loading runs…</p>}

        {runs.data && runs.data.runs.length === 0 && (
          <Card>
            <CardContent className="pt-6 text-sm text-slate-500">
              No runs yet. As soon as a workflow run is recorded, it appears here automatically.
            </CardContent>
          </Card>
        )}

        <div className="space-y-3">
          {(runs.data?.runs || []).map((r) => (
            <Card key={r.id} className="cursor-pointer transition hover:shadow-md">
              <CardHeader className="pb-2" onClick={() => setSelectedId(r.id)}>
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base">{r.workflowName || "Workflow"}</CardTitle>
                  <StatusBadge status={r.status} />
                </div>
                <CardDescription>
                  {r.startedAt ? `Started ${new Date(r.startedAt).toLocaleString()}` : "Not started"}
                  {r.completedAt ? ` · Finished ${new Date(r.completedAt).toLocaleString()}` : ""}
                  {r.errorMessage ? ` · Error: ${r.errorMessage}` : ""}
                </CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>

        {selectedId && (
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Run detail</CardTitle>
                  <CardDescription>
                    {detail.data
                      ? `Total measured cost $${detail.data.totalCost} across ${detail.data.steps.length} steps · ${detail.data.totalLatencyMs} ms total agent time`
                      : "Loading…"}
                  </CardDescription>
                </div>
                <Button variant="outline" size="sm" onClick={() => setSelectedId(null)}>
                  Close
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {detail.isError && (
                <p className="text-sm text-red-600">{(detail.error as Error).message}</p>
              )}
              {detail.data && (
                <>
                  <div>
                    <h3 className="mb-2 text-sm font-semibold text-slate-700">Steps</h3>
                    <div className="space-y-2">
                      {detail.data.steps.map((s) => (
                        <div
                          key={s.id}
                          className="flex items-center justify-between rounded-md border border-slate-200 p-2 text-sm"
                        >
                          <StatusBadge status={s.status} />
                          <span className="text-slate-600">
                            {s.latencyMs != null ? `${s.latencyMs} ms` : "latency not reported"}
                            {" · "}
                            {s.cost != null ? `$${s.cost}` : "cost not reported"}
                          </span>
                          {s.errorMessage && (
                            <span className="text-xs text-red-600">{s.errorMessage}</span>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <h3 className="mb-2 text-sm font-semibold text-slate-700">Artifacts</h3>
                    {detail.data.artifacts.length === 0 && (
                      <p className="text-sm text-slate-500">No artifacts produced by this run.</p>
                    )}
                    <div className="space-y-2">
                      {detail.data.artifacts.map((a) => (
                        <div key={a.id} className="rounded-md border border-slate-200 p-3">
                          <div className="flex items-center justify-between">
                            <p className="text-sm font-medium text-slate-900">{a.title}</p>
                            <StatusBadge status={a.status} />
                          </div>
                          <p className="mt-1 text-xs text-slate-500">
                            {a.artifactType} ·{" "}
                            {a.qualityScore != null
                              ? `quality ${a.qualityScore}${a.qualityGrade ? ` (${a.qualityGrade})` : ""}`
                              : "quality not evaluated"}
                          </p>
                          {a.summary && <p className="mt-1 text-sm text-slate-600">{a.summary}</p>}
                        </div>
                      ))}
                    </div>
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        )}

        <p className="pb-6 text-center text-xs text-slate-400">
          This report refreshes every 15 seconds while the page is open.
        </p>
      </div>
    </div>
  );
}

function HonestEmpty({ title, body }: { title: string; body: string }) {
  return (
    <div className="flex min-h-screen items-center justify-center bg-slate-50 p-6">
      <Card className="max-w-md">
        <CardHeader>
          <CardTitle>{title}</CardTitle>
          <CardDescription>{body}</CardDescription>
        </CardHeader>
      </Card>
    </div>
  );
}
