/**
 * Render the final swarm output as a markdown report.
 * Used both for terminal display (via stdout) and for posting back to the PR.
 */

export function renderReport({ prData, reviews, synthesis }) {
  const header = `# 🤠 PR Posse Review

**PR**: [#${prData.number} — ${prData.title}](${prData.url})
**Repo**: \`${prData.repo}\`
**Author**: @${prData.author}
**Branch**: \`${prData.head}\` → \`${prData.base}\`
**Stats**: +${prData.additions} / -${prData.deletions} across ${prData.changedFiles} file(s)
`;

  const synth = `\n---\n\n${synthesis.trim()}\n`;

  const detail =
    `\n---\n\n<details>\n<summary>🔍 Individual specialist reports</summary>\n\n` +
    reviews.map(r =>
      `### ${r.emoji} ${r.name}\n\n${r.output.trim()}\n`
    ).join('\n') +
    `\n</details>\n`;

  const footer = `\n---\n_Generated by [PR Posse](https://github.com/) — a swarm of ${reviews.length} parallel reviewers + 1 synthesizer, orchestrated with [agentic-flow](https://www.npmjs.com/package/agentic-flow)._\n`;

  return header + synth + detail + footer;
}
