import type { Request, Response } from "express";
import { eq, desc, and, asc } from "drizzle-orm";
import { getDb } from "../db";
import { workflowArtifacts, workflowRuns, workflows } from "../schema";
import fs from "fs";
import path from "path";
import { evaluateArtifactQuality, buildRefinementPrompt } from "../execution/quality-evaluator";
import { generateText } from "ai";
import { createGoogleGenerativeAI } from "@ai-sdk/google";

/**
 * List all workflow artifacts for the active workspace.
 */
export async function listArtifacts(req: Request, res: Response): Promise<void> {
  try {
    const workspaceId = req.workspaceId;
    if (!workspaceId) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const { type, status, runId, limit = "50" } = req.query;

    const db = await getDb();
    if (!db) {
      res.status(503).json({ error: "Database unavailable" });
      return;
    }

    const conditions = [eq(workflowArtifacts.workspaceId, workspaceId)];

    if (type && typeof type === "string" && type !== "all") {
      conditions.push(eq(workflowArtifacts.artifactType, type));
    }
    if (status && typeof status === "string" && status !== "all") {
      conditions.push(eq(workflowArtifacts.status, status));
    }
    if (runId && typeof runId === "string") {
      conditions.push(eq(workflowArtifacts.workflowRunId, runId));
    }

    const artifacts = await db
      .select()
      .from(workflowArtifacts)
      .where(and(...conditions))
      .orderBy(desc(workflowArtifacts.createdAt))
      .limit(parseInt(limit as string, 10));

    res.status(200).json({
      workspaceId,
      artifacts,
      totalCount: artifacts.length,
    });
  } catch (error) {
    console.error("[Artifacts Controller Error]:", error);
    res.status(500).json({ error: "Failed to list artifacts" });
  }
}

/**
 * Get Content Calendar: specifically retrieves posts, drafts, and scheduled items formatted for calendar view.
 */
export async function getContentCalendar(req: Request, res: Response): Promise<void> {
  try {
    const workspaceId = req.workspaceId;
    if (!workspaceId) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const db = await getDb();
    if (!db) {
      res.status(503).json({ error: "Database unavailable" });
      return;
    }

    // Query all post artifacts
    const postArtifacts = await db
      .select()
      .from(workflowArtifacts)
      .where(
        and(
          eq(workflowArtifacts.workspaceId, workspaceId),
          eq(workflowArtifacts.artifactType, "post")
        )
      )
      .orderBy(asc(workflowArtifacts.scheduledFor), desc(workflowArtifacts.createdAt))
      .limit(100);

    // Also check if local Content-Queue.md has active drafts to surface
    let localQueueSummary = "";
    const queuePath = path.resolve(process.cwd(), "Agent Lab LinkedIn", "Content-Queue.md");
    if (fs.existsSync(queuePath)) {
      try {
        localQueueSummary = fs.readFileSync(queuePath, "utf-8").substring(0, 10000);
      } catch (e) {
        console.warn("Could not read local Content-Queue.md:", e);
      }
    }

    res.status(200).json({
      workspaceId,
      calendarItems: postArtifacts,
      totalScheduled: postArtifacts.filter(a => a.status === "scheduled").length,
      totalDrafts: postArtifacts.filter(a => a.status === "draft").length,
      totalPublished: postArtifacts.filter(a => a.status === "published").length,
      localContentQueueExcerpt: localQueueSummary,
    });
  } catch (error) {
    console.error("[Content Calendar Controller Error]:", error);
    res.status(500).json({ error: "Failed to fetch content calendar" });
  }
}

/**
 * Get artifacts generated by a specific workflow run.
 */
export async function getRunArtifacts(req: Request, res: Response): Promise<void> {
  try {
    const workspaceId = req.workspaceId;
    if (!workspaceId) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const { runId } = req.params;

    const db = await getDb();
    if (!db) {
      res.status(503).json({ error: "Database unavailable" });
      return;
    }

    const artifacts = await db
      .select()
      .from(workflowArtifacts)
      .where(
        and(
          eq(workflowArtifacts.workspaceId, workspaceId),
          eq(workflowArtifacts.workflowRunId, runId)
        )
      )
      .orderBy(asc(workflowArtifacts.createdAt));

    res.status(200).json({ runId, artifacts });
  } catch (error) {
    console.error("[Run Artifacts Error]:", error);
    res.status(500).json({ error: "Failed to fetch run artifacts" });
  }
}

/**
 * Update artifact status (e.g. draft -> scheduled, scheduled -> published).
 */
export async function updateArtifactStatus(req: Request, res: Response): Promise<void> {
  try {
    const workspaceId = req.workspaceId;
    if (!workspaceId) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const { id } = req.params;
    const { status, scheduledFor } = req.body;

    const db = await getDb();
    if (!db) {
      res.status(503).json({ error: "Database unavailable" });
      return;
    }

    const updateData: any = { updatedAt: new Date() };
    if (status) updateData.status = status;
    if (scheduledFor) updateData.scheduledFor = new Date(scheduledFor);

    await db
      .update(workflowArtifacts)
      .set(updateData)
      .where(
        and(
          eq(workflowArtifacts.id, id),
          eq(workflowArtifacts.workspaceId, workspaceId)
        )
      );

    res.status(200).json({ success: true, message: "Artifact status updated" });
  } catch (error) {
    console.error("[Update Artifact Error]:", error);
    res.status(500).json({ error: "Failed to update artifact status" });
  }
}

/**
 * Download raw artifact contents (e.g. as markdown or csv file).
 */
export async function downloadArtifact(req: Request, res: Response): Promise<void> {
  try {
    const workspaceId = req.workspaceId;
    if (!workspaceId) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const { id } = req.params;

    const db = await getDb();
    if (!db) {
      res.status(503).json({ error: "Database unavailable" });
      return;
    }

    const artifacts = await db
      .select()
      .from(workflowArtifacts)
      .where(
        and(
          eq(workflowArtifacts.id, id),
          eq(workflowArtifacts.workspaceId, workspaceId)
        )
      )
      .limit(1);

    if (artifacts.length === 0) {
      res.status(404).json({ error: "Artifact not found" });
      return;
    }

    const artifact = artifacts[0];
    const safeTitle = (artifact.title || "artifact")
      .toLowerCase()
      .replace(/[^a-z0-9_-]/g, "-")
      .slice(0, 40);

    const extension = artifact.artifactType === "csv" ? "csv" : "md";
    const filename = `${safeTitle}-${artifact.id.slice(0, 6)}.${extension}`;

    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Type", extension === "csv" ? "text/csv; charset=utf-8" : "text/markdown; charset=utf-8");
    res.status(200).send(artifact.content);
  } catch (error) {
    console.error("[Download Artifact Error]:", error);
    res.status(500).json({ error: "Failed to download artifact" });
  }
}

/**
 * Evaluate an artifact's quality score, grade, and brand alignment on demand.
 */
export async function evaluateArtifact(req: Request, res: Response): Promise<void> {
  try {
    const workspaceId = req.workspaceId;
    if (!workspaceId) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const { id } = req.params;

    const db = await getDb();
    if (!db) {
      res.status(503).json({ error: "Database unavailable" });
      return;
    }

    const artifacts = await db
      .select()
      .from(workflowArtifacts)
      .where(and(eq(workflowArtifacts.id, id), eq(workflowArtifacts.workspaceId, workspaceId)))
      .limit(1);

    if (artifacts.length === 0) {
      res.status(404).json({ error: "Artifact not found" });
      return;
    }

    const artifact = artifacts[0];
    const evaluation = evaluateArtifactQuality({
      title: artifact.title,
      content: artifact.content,
      targetPlatform: artifact.targetPlatform,
      artifactType: artifact.artifactType,
    });

    await db
      .update(workflowArtifacts)
      .set({
        qualityScore: evaluation.score,
        qualityGrade: evaluation.grade,
        verificationNotes: {
          feedback: evaluation.feedback,
          suggestions: evaluation.suggestions,
          passed: evaluation.passed,
          rubric: evaluation.rubric,
          evaluatedAt: evaluation.evaluatedAt,
        },
        updatedAt: new Date(),
      })
      .where(and(eq(workflowArtifacts.id, id), eq(workflowArtifacts.workspaceId, workspaceId)));

    res.status(200).json({
      success: true,
      artifactId: id,
      evaluation,
    });
  } catch (error) {
    console.error("[Evaluate Artifact Error]:", error);
    res.status(500).json({ error: "Failed to evaluate artifact" });
  }
}

/**
 * Refine an artifact using operator instructions or automated quality recommendations.
 */
export async function refineArtifact(req: Request, res: Response): Promise<void> {
  try {
    const workspaceId = req.workspaceId;
    if (!workspaceId) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const { id } = req.params;
    const { instructions } = req.body;

    const db = await getDb();
    if (!db) {
      res.status(503).json({ error: "Database unavailable" });
      return;
    }

    const artifacts = await db
      .select()
      .from(workflowArtifacts)
      .where(and(eq(workflowArtifacts.id, id), eq(workflowArtifacts.workspaceId, workspaceId)))
      .limit(1);

    if (artifacts.length === 0) {
      res.status(404).json({ error: "Artifact not found" });
      return;
    }

    const original = artifacts[0];
    const initialEval = evaluateArtifactQuality({
      title: original.title,
      content: original.content,
      targetPlatform: original.targetPlatform,
      artifactType: original.artifactType,
    });

    let refinedContent = original.content;

    // Use Gemini if available
    const apiKey =
      process.env.GOOGLE_GENERATIVE_AI_API_KEY ||
      process.env.GEMINI_API_KEY ||
      process.env.AI_STUDIO_API_KEY;

    if (apiKey) {
      try {
        const google = createGoogleGenerativeAI({ apiKey });
        const model = google("gemini-2.5-flash");
        const prompt = buildRefinementPrompt(original.content, instructions, initialEval);

        const aiResponse = await generateText({
          model,
          prompt,
          system:
            "You are an elite operational copywriter and agency strategist for URC & AgentLab. You produce crisp, authentic, high-impact copy with zero generic filler.",
          temperature: 0.3,
        });

        if (aiResponse.text && aiResponse.text.trim()) {
          refinedContent = aiResponse.text.trim();
        }
      } catch (aiErr) {
        console.warn("[RefineArtifact] AI generation fallback:", aiErr);
      }
    }

    // If AI was not used or returned same content, apply deterministic heuristic cleanup
    if (refinedContent === original.content) {
      refinedContent = refinedContent
        .replace(/\[(?:INSERT|YOUR|COMPANY|NAME|LINK|DATE|RECIPIENT|PROMPT|URL|PHONE|CLIENT)[^\]]*\]/gi, "URC / AgentLab")
        .replace(/in today'?s fast[- ]paced (?:world|digital landscape|environment),?/gi, "")
        .replace(/revolutionary game[- ]changer/gi, "high-leverage operating system")
        .trim();
      if (instructions) {
        refinedContent += `\n\n*(Refinement Note: Applied operator instruction - ${instructions})*`;
      }
    }

    // Re-evaluate refined content
    const newEval = evaluateArtifactQuality({
      title: original.title,
      content: refinedContent,
      targetPlatform: original.targetPlatform,
      artifactType: original.artifactType,
    });

    const newRevisionVersion = (original.revisionVersion || 1) + 1;
    const newArtifactId = crypto.randomUUID();

    // Insert new revised artifact
    await db.insert(workflowArtifacts).values({
      id: newArtifactId,
      workspaceId,
      workflowRunId: original.workflowRunId,
      workflowRunStepId: original.workflowRunStepId,
      workflowId: original.workflowId,
      artifactType: original.artifactType,
      title: `${original.title} (v${newRevisionVersion})`,
      content: refinedContent,
      summary: original.summary,
      status: original.status,
      scheduledFor: original.scheduledFor,
      targetPlatform: original.targetPlatform,
      qualityScore: newEval.score,
      qualityGrade: newEval.grade,
      verificationNotes: {
        feedback: newEval.feedback,
        suggestions: newEval.suggestions,
        passed: newEval.passed,
        rubric: newEval.rubric,
        evaluatedAt: newEval.evaluatedAt,
        refinementInstructions: instructions || "Auto-refined quality flywheel",
      },
      revisionVersion: newRevisionVersion,
      parentArtifactId: original.id,
      metadata: {
        ...(original.metadata || {}),
        refinedFrom: original.id,
        refinedAt: new Date().toISOString(),
      },
    } as any);

    res.status(200).json({
      success: true,
      originalArtifactId: original.id,
      refinedArtifactId: newArtifactId,
      refinedContent,
      revisionVersion: newRevisionVersion,
      evaluation: newEval,
    });
  } catch (error) {
    console.error("[Refine Artifact Error]:", error);
    res.status(500).json({ error: "Failed to refine artifact" });
  }
}

